config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # get 'conversations/index'

  # get 'conversations/create'

  # get 'conversations/update'

  resources :conversations, only: [:create]

  get 'chat/index'

  get 'chat/show'

  get 'chat/edit'

  get 'chat/update'

  get 'admin/index'

  get 'admin/login'

  get 'admin/show'

  resources :bounties
  root 'welcome#index'

  get 'welcome/show'

  devise_for :users
  resources :products

  get '/admin' => 'admin#login'
  get '/dashboard' => 'admin#index'
  get '/change_status/:id' => 'admin#change_status'
  get '/change_user_status/:id' => 'admin#change_user_status'
  resources :users
  get '/bounty/:id' => 'welcome#show'
  post '/participate' => 'welcome#participate'
  get '/create_profile' => 'users#create_profile'
  post '/upload_template' => 'users#upload_template'
  get '/upload_template_header' => 'users#upload_template_header'
  # resources :conversations, only: [:create]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  resources :conversations do
    resources :messages
  end
  # resources :conversations do 
  #   resources :messages, only: [:create]
  # end

  resources :comments, only: [:index, :new, :create]

  mount ActionCable.server => '/cable'

  #   require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'


end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  
  field :body, type: String
  field :user_id, type: String
  field :bounty_id, type: String

  belongs_to :user
  belongs_to :bounty
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @bounty = Bounty.find(params[:comment]["bounty_id"])
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        # format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js {  }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :bounty_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<!-- <div class="container"> -->
  <!-- <div class="row"> -->
    <div class="col-md-12">
      <div class="page-header" style="margin-top:0;">
        <h1><small class="pull-right"><%= (@bounty.comments.count == 0) ? 'No' : @bounty.comments.count %> comments</small> Comments </h1>
      </div> 
      <div class="comments-list">
        <% @bounty.comments.each do |comment| %>
          <div class="media">
            <div class="col-xs-12">
              <div class="col-xs-1">
                <%= image_tag(comment_user_avatar(comment.user), :style=>'width:30px;') %>
              </div>
              <div class="col-xs-9">
                <h4 class="media-heading user_name"><%= comment.body %></h4>
                <%= comment.user.email %>
              </div>
              <div class="col-xs-2">
              <p class="pull-right"><small><%= time_ago_in_words((comment.created_at || Time.now)) %></small></p>
            </div>
            </div>
            
          </div>
        <% end %>
      </div>
    </div>
  <!-- </div> -->
<!-- </div> -->

app/views/comments/_form.html.erb
<!-- <div class="container"> -->
  <!-- <div class="row"> -->
    <div class="col-md-12">
      <%= form_with(model: comment,  remote: true) do |form| %>
        <% if comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
            <% comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field" style="margin-top:5%;">
          <%= form.text_area :body, id: :comment_body, :class => 'form-control', :rows => 5 %>
        </div>

        <%= hidden_field_tag 'comment[user_id]', current_user.id %>
        <%= hidden_field_tag 'comment[bounty_id]', @bounty.id %>

        <div class="actions" style="text-align:right;">
          <%= form.submit('Comment', :class => 'btn btn-success') %>
        </div>
      <% end %>
    </div>
  <!-- </div> -->
<!-- </div> -->

app/views/comments/create.js.erb
$("#comment_list").html('<%= raw escape_javascript(render(partial: "comments")) %>');
$('#comment_body').val('');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Bounty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.bounty_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Bounty:</strong>
  <%= @comment.bounty_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>