config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # get 'conversations/index'

  # get 'conversations/create'

  # get 'conversations/update'

  resources :conversations, only: [:create]

  get 'chat/index'

  get 'chat/show'

  get 'chat/edit'

  get 'chat/update'

  get 'admin/index'

  get 'admin/login'

  get 'admin/show'

  resources :bounties
  root 'welcome#index'

  get 'welcome/show'

  devise_for :users
  resources :products

  get '/admin' => 'admin#login'
  get '/dashboard' => 'admin#index'
  get '/change_status/:id' => 'admin#change_status'
  get '/change_user_status/:id' => 'admin#change_user_status'
  resources :users
  get '/bounty/:id' => 'welcome#show'
  post '/participate' => 'welcome#participate'
  get '/create_profile' => 'users#create_profile'
  post '/upload_template' => 'users#upload_template'
  get '/upload_template_header' => 'users#upload_template_header'
  # resources :conversations, only: [:create]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  resources :conversations do
    resources :messages
  end
  # resources :conversations do 
  #   resources :messages, only: [:create]
  # end

  resources :comments, only: [:index, :new, :create]

  mount ActionCable.server => '/cable'

  #   require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'


end

app/models/conversation.rb
class Conversation 
  include Mongoid::Document

  field :recipient_id, type: String 
  field :sender_id, type: String


  has_many :messages, dependent: :destroy
  # belongs_to :sender, foreign_key: :sender_id, class_name: User
  # belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  # validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    a = where(sender_id: sender_id, recipient_id: recipient_id) 
    b = where(sender_id: recipient_id, recipient_id: sender_id) 
    if a.blank?
      b
    else
      a
    end
  end
  # scope :between, -> (sender_id,recipient_id) do
  #   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  # end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?
    create(sender_id: sender_id, recipient_id: recipient_id) unless recipient_id.blank?
  end

  def opposed_user(user)    
    if self.recipient_id==user.id.to_s
      User.find(self.sender_id)
    else
      User.find(self.recipient_id)
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    # @conversation = Conversation.get(current_user.id.to_s, params[:user_id])
    # add_to_conversations unless conversated?
    redirect_to conversation_messages_path(@conversation)
    # respond_to do |format|
    #   format.js
    # end
  end

  def close
    @conversation = Conversation.find(params[:id])
 
    session[:conversations].delete(@conversation.id)
 
    respond_to do |format|
      format.js
    end
  end
 
  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
 
  # def add_to_conversations
  #   session[:conversations] ||= []
  #   session[:conversations] << @conversation.id rescue nil
  # end
 
  # def conversated?
  #   session[:conversations].include?(@conversation.id) rescue nil
  # end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= link_to conversation.opposed_user(user).email, '', class: 'toggle-window' %>
      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
    </div>

    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
      <%#= form_for [conversation, conversation.messages.new], remote: true do |f| %>
        <%#= f.hidden_field :user_id, value: user.id %>
        <%#= f.text_area :body, class: "form-control" %>
        <%#= f.submit "Send", class: "btn btn-success" %>
      <%# end %>

      <%= form_for [conversation, conversation.messages.new], html: {class: "ui reply form"} do |f| %>
        <div class="field">
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
        <div>
          <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
      </div>

<% end %>

      <form class="new_message">
        <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
        <input name="user_id" type="hidden" value="<%= user.id %>">
        <textarea name="body" class="form-control"></textarea>
        <input type="submit" class="btn btn-success" value="Send">
      </form>

    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.html.erb
<h1>Conversations#create</h1>
<p>Find me in app/views/conversations/create.html.erb</p>

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
 
if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}
 
conversation.find('.panel-body').show();
 
var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/conversations/index.html.erb
<!-- <h1>Conversations#index</h1>
<p>Find me in app/views/conversations/index.html.erb</p>
 -->

 <div class="ui segment">
  <h3>Mailbox</h3>

  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id.to_s || conversation.recipient_id == current_user.id.to_s %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <%= link_to recipient.email, conversation_messages_path(conversation)%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/update.html.erb
<h1>Conversations#update</h1>
<p>Find me in app/views/conversations/update.html.erb</p>