config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # get 'conversations/index'

  # get 'conversations/create'

  # get 'conversations/update'

  resources :conversations, only: [:create]

  get 'chat/index'

  get 'chat/show'

  get 'chat/edit'

  get 'chat/update'

  get 'admin/index'

  get 'admin/login'

  get 'admin/show'

  resources :bounties
  root 'welcome#index'

  get 'welcome/show'

  devise_for :users
  resources :products

  get '/admin' => 'admin#login'
  get '/dashboard' => 'admin#index'
  get '/change_status/:id' => 'admin#change_status'
  get '/change_user_status/:id' => 'admin#change_user_status'
  resources :users
  get '/bounty/:id' => 'welcome#show'
  post '/participate' => 'welcome#participate'
  get '/create_profile' => 'users#create_profile'
  post '/upload_template' => 'users#upload_template'
  get '/upload_template_header' => 'users#upload_template_header'
  # resources :conversations, only: [:create]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  resources :conversations do
    resources :messages
  end
  # resources :conversations do 
  #   resources :messages, only: [:create]
  # end

  resources :comments, only: [:index, :new, :create]

  mount ActionCable.server => '/cable'

  #   require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'


end

app/views/admin/index.html.erb
<%= render 'bounties/bounty_list' %>

app/views/admin/login.html.erb
<h2>Login</h2>
<div class="login-page">
  <div class="form">
    <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:class => "login-form"}) do |f| %>
      <%= devise_error_messages! %>
      <%= f.email_field :email, autofocus: true, placeholder: 'username' %>
      <%= f.password_field :password, autocomplete: "off", placeholder: 'password' %>
      <% if devise_mapping.rememberable? -%>
        <div class="form-check remember-me-block">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>
      <%= f.submit "Log in", class: "submit" %>
    <% end %>
  </div>
</div>

app/views/admin/show.html.erb
<h1>Admin#show</h1>
<p>Find me in app/views/admin/show.html.erb</p>