config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # get 'conversations/index'

  # get 'conversations/create'

  # get 'conversations/update'

  resources :conversations, only: [:create]

  get 'chat/index'

  get 'chat/show'

  get 'chat/edit'

  get 'chat/update'

  get 'admin/index'

  get 'admin/login'

  get 'admin/show'

  resources :bounties
  root 'welcome#index'

  get 'welcome/show'

  devise_for :users
  resources :products

  get '/admin' => 'admin#login'
  get '/dashboard' => 'admin#index'
  get '/change_status/:id' => 'admin#change_status'
  get '/change_user_status/:id' => 'admin#change_user_status'
  resources :users
  get '/bounty/:id' => 'welcome#show'
  post '/participate' => 'welcome#participate'
  get '/create_profile' => 'users#create_profile'
  post '/upload_template' => 'users#upload_template'
  get '/upload_template_header' => 'users#upload_template_header'
  # resources :conversations, only: [:create]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  resources :conversations do
    resources :messages
  end
  # resources :conversations do 
  #   resources :messages, only: [:create]
  # end

  resources :comments, only: [:index, :new, :create]

  mount ActionCable.server => '/cable'

  #   require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	# @bounties = Bounty.where(status:"approved")
    @bounties = Bounty.where(status:"approved")
  end

  def show
    @comment = Comment.new
  	@bounty = Bounty.find(params[:id])
  end

  def participate
  	unless current_user.blank?
  		@flag = true
  		if verify_recaptcha(model: @user)
  			@bounty = Bounty.find(params[:id])
        Participant.create(user_id: current_user.id,bounty_id: @bounty.id)
  		else
  			@flag = false
  		end
  		respond_to do |format|
        	format.js {}
      	end
  	end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def comment_user_avatar(user)
		email_address = user.email.downcase
		# create the md5 hash
		hash = Digest::MD5.hexdigest(email_address)
		# compile URL which can be used in https://www.gravatar.com/avatar/#{hash}"
		profile_img = 'https://www.gravatar.com/avatar/'+hash
	  if profile_img.blank?
	  	'login_logo.png'
	  else
	  	profile_img
	  end			
	end
end

app/views/welcome/_footer.html.erb
<div class = "col-sm-12 padding-15 footer-bg white-text" id = "landing-footer" style="padding-top: 2%; margin-bottom: -2px;">
	<div class = "bounty-flex b-flex-space-between">
		<a href = ""><span class="line-height-40">Terms and Conditions</span></a>
		<a href = ""><span class="line-height-40">How it works</span></a>
		<a href = ""><span class="line-height-40">About Us</span></a>
		<a href = ""><span class="line-height-40">Blog</span></a>
		<a href = ""><span class="line-height-40">FAQs</span></a>
		<a href = ""><span class="line-height-40">Contact us &amp; Support</span></a>
		<a href = ""><span class="line-height-40">Social media links</span></a>
	</div>
	<div class = "bounty-flex b-flex-start"><a href = ""><span class="line-height-40">Privacy Policy</span></a></div>
	<div class = "bounty-flex b-flex-start"><a href = ""><span class="line-height-40">Use of Cookies</span></a></div>
	<div class = "bounty-flex b-flex-start"><a href = ""><span class="line-height-40">Insurance Coverage</span></a></div>
	<div class = "bounty-flex b-flex-start"><a href = ""><span class="line-height-40">Careers</span></a></div>
</div>
<div id = "footer-responsive" class = "footer-bg white-text" style="display: flex; flex-wrap: wrap;">
	<a href = ""><span class="line-height-40">Terms and Conditions</span></a>
	<a href = ""><span class="line-height-40">How it works</span></a>
	<a href = ""><span class="line-height-40">About Us</span></a>
	<a href = ""><span class="line-height-40">Blog</span></a>
	<a href = ""><span class="line-height-40">FAQs</span></a>
	<a href = ""><span class="line-height-40">Contact us &amp; Support</span></a>
	<a href = ""><span class="line-height-40">Social media links</span></a>
	<a href = ""><span class="line-height-40">Privacy Policy</span></a>
	<a href = ""><span class="line-height-40">Use of Cookies</span></a>
	<a href = ""><span class="line-height-40">Insurance Coverage</span></a>
	<a href = ""><span class="line-height-40">Careers</span></a>
</div>

app/views/welcome/_header_2.html.erb
<div id="mySidenav" class="sidenav">
  <ul style="padding-left:20px;">  
    <li><a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a></li>
    <li><a href = "/">HOME</a></li>
    <% if current_user.present? %>
		<% if current_user.roles == :admin %>
			<li><a href = "/users">USERS</a></li>
		<% end %>
	<% end %>
    <li><a href="">ICONS</a></li>
    <% if current_user.present? %>
		<% if current_user.roles == :organizer || current_user.roles == :admin %>
			<li><a href="/bounties">BOUNTY</a></li>
		<% end %>
	<% end %>
    <li><a href="">ADD YOUR BOUNTY</a></li>
    <% if current_user.present? %>
		<% if current_user.roles == :admin %>
			<li><a href = "/upload_template_header">UPLOAD TEMPLATE</a></li>
		<% end %>
	<% end %>
    <% if user_signed_in? %>
		<li><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %></li>
		
	<% else %>
		<li><%= link_to "LOGIN", new_user_session_path %></li>
		<li><%= link_to "SIGN UP", '/create_profile' %></li>
	<% end %>
  </ul>  
</div>
<div id = "mob-menu-click-main">
  <div id = "mob-menu-click-bar" style="" onclick="openNav()">&#9776;</div>
</div>
<div class = "col-sm-12 padding10 header-bg white-text top-header-menu" id = "header-top">
	<div class = "col-sm-4">
		<span class = "size24 white-text"><a href= "">Bounty Monster</a></span>
	</div>
	<div class = "col-sm-8">
	<div class = "bounty-flex b-flex-space-around">
	<span class="icon-bar"><a href = "/">HOME</a></span>
	<% if current_user.present? %>
		<% if current_user.roles == :admin %>
			<span class="icon-bar"><a href = "/users">USERS</a></span>
		<% end %>
	<% end %>
	<span class="icon-bar"><a href = "">ICONS</a></span>
	<% if current_user.present? %>
		<% if current_user.roles == :organizer || current_user.roles == :admin%>
			<span class="icon-bar"><a href="/bounties">BOUNTY</a></span>
		<% end %>
	<% end %>
	<span class="icon-bar"><a href = "">ADD YOUR BOUNTY</a></span>
	<% if current_user.present? %>
		<% if current_user.roles == :admin %>
			<span class="icon-bar"><a href = "/upload_template_header">UPLOAD TEMPLATE</a></span>
		<% end %>
	<% end %>
	<% if user_signed_in? %>
		<span class="icon-bar"><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %></span>
	<% else %>
		<span class="icon-bar"><%= link_to "LOGIN", new_user_session_path %></span>
		<span class="icon-bar"><%= link_to "SIGN UP", '/create_profile' %></span>
	<% end %>
	</div>
	</div>
</div>
<script type="text/javascript">
	function openNav() {
		document.getElementById("mySidenav").style.width = "250px";
		document.getElementById("mySidenav").style.padding = "5%";
	}
	function closeNav() {
		document.getElementById("mySidenav").style.width = "0";
		document.getElementById("mySidenav").style.padding = "0";
	}
</script>

app/views/welcome/_landing_page_header.html.erb
<%= render 'welcome/header_2' %>
<div class="well well-lg text-center bounty-flex b-flex-center white-text header-bg header-len zero-border zero-border-radius" id = "header-big">
	<div>
		<div class = "size24 line-height-40">Your heading here</div>
		<div>Signup Now &amp; Get one month premium membership for free!</div>
	</div>
</div>

app/views/welcome/_menu_boxes.html.erb
<div class= "row padding20 margin5" id = "menu_boxes">
	<div class = "bounty-flex b-flex-space-around">
		<div class = "bounty-flex b-flex-column b-flex-center menu-img-box">
			<span>ENVION</span>
			<%= image_tag 'volinex.jpg', class: 'menu-img' %>
		</div>
		<div class = "bounty-flex b-flex-column b-flex-center menu-img-box">
			<span>VOLINEX</span>
			<%= image_tag 'volinex.jpg', class: 'menu-img' %>
		</div>
		<div class = "bounty-flex b-flex-column b-flex-center menu-img-box">
			<span>KRIOS</span>
			<%= image_tag 'krios.jpg', class: 'menu-img' %>
		</div>
		<div class = "bounty-flex b-flex-column b-flex-center menu-img-box">
			<span>CLN</span>
			<%= image_tag 'cln.jpg', class: 'menu-img' %>
		</div>
		<div class = "bounty-flex b-flex-column b-flex-center menu-img-box">
			<span>DADI</span>
			<%= image_tag 'dadi.jpg', class: 'menu-img' %>
		</div>
	</div>
</div>

app/views/welcome/_recaptcha_modal_to_participate.html.erb
<div class="modal fade" id="recaptchaparticipate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
      <p id = "message">Please verify recaptcha to submit</p>
      <%= form_tag('/participate?id='+@bounty.id, remote: true)  do %>
        <fieldset>
          <%= recaptcha_tags %>
          <button type="button" class="btn btn-default close-participate-modal" data-dismiss="modal">cancel</button>
          <%= submit_tag "submit", class: "btn btn-success" %>
        </fieldset>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%#= render "landing_page_header" %>
<div class="container" >
	<%= render 'menu_boxes' %>
	<div class="row padding10">
		<% unless @bounties.blank? %>
			<% @bounties.each do |bounty| %>
				<a href = "/bounty/<%= bounty.id %>">
					<div class="col-sm-4">
						<div class="well white-bg">
							<div>
								<%= image_tag 'cln.jpg', class: "grid-crypto-sym" %>
								<h3 style="display:inline; vertical-align:middle;margin-left:2%;"><%= bounty.name.capitalize rescue 'Not Available'%></h3>
							</div>
							<div class = "line-height-40"><span class="grid-goal-text">Goal: &#036;<%= bounty.goal %></span><span class="grid-goal-text2">/3000</span></div>
							<div>Countdown to End of Project</div><br/>
							<div class = "bounty-flex b-flex-center">	
								<div class = "col-xs-10 zero-padding">
									<div class="progress" style="height:8px; margin-bottom:0px;">
										<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 50%; height:8px;"></div>
									</div>
								</div>
								<div class = "col-xs-2">
									<div class = "grey-text grey-bold">50%</div>
								</div>
							</div>
							<br/>
							<div class = "round-progress-bars bounty-flex b-flex-center">
								<div class="progress-bar position" data-percent="40" data-duration="1000" data-color="#ededed,#428bca"></div>
								<div class="progress-bar position" data-percent="50" data-duration="1000" data-color="#ededed,#cc9c77"></div>
								<div class="progress-bar position" data-percent="60" data-color="#ededed,#84ca9a"></div>
								<div class="progress-bar position" data-percent="70" data-color="#ededed,#a93755"></div>
							</div>
						</div>
					</div>
				</a>
			<% end %>
		<% else %>
			<h3 class = "text-center">No Bounties Available </p>
		<% end %>
	</div>
</div>
<%= render 'welcome/footer' %>
<script>
	$(".round-progress-bars .progress-bar").loading();
	$('input').on('click', function () {
			$(".progress-bar").loading();
	});
</script>
<!-- test -->

<!-- test -->
<!-- defe -->

app/views/welcome/participate.js.erb
<% unless @flag == true %>
	$("#recaptchaparticipate #message").html("Please verify recaptcha first");
<% else %>
	$("#recaptchaparticipate .modal-body").html("<p>You have participated successfully</p>");
	<% user_id = User.find(@bounty.organizer_id).id %>
	$('.participate-btn').replaceWith('<a class="btn btn-primary pull-right participate-btn" href="/chat/index?user_id=<%= user_id %>">Chat</a>')
<% end %>

app/views/welcome/show.html.erb
<%= render "recaptcha_modal_to_participate" %>
<!-- <div class="container" style="border-bottom: 1px dotted;
    padding-bottom: 1%;"> -->
<article>
	<div class="row">
		<div class = "col-lg-10 col-lg-offset-1">
			<div class = "col-xs-12" style="background:#fff;padding:40px;box-shadow: 0 2px 6px rgba(0,0,0,.1);margin:0px;">
				<% unless current_user.blank? %>
				  <% if Participant.where(user_id: current_user.id,bounty_id: @bounty.id).blank? %>
					  <button class = "btn btn-primary pull-right participate-btn" data-toggle="modal" data-target="#recaptchaparticipate">Participate</button>
					<% else %>
						<%#= link_to 'Chat', chat_index_path+"?user_id="+User.find(@bounty.organizer_id).id, :class => "btn btn-primary pull-right participate-btn" %>
						<!-- <button class = "btn btn-primary pull-right participate-btn" >Participated</button> -->
					<% end %>
				<% else %>
					<%= link_to "Participate", "/users/sign_in", class: "btn btn-primary pull-right" %>
				<% end %>
				<div class = "bounty-mon-row">
				<div class = "col-md-12">
				<h3>Bounty Name</h3>
				Decentralizing Short-Term Housing Rentals. Blockchain Powered Platform With 0% Commissions, Network Effects, Bank-Level Security, and Immutable Reviews
				</div>
				</div>
				<div class = "bounty-mon-row">
				<div class = "col-md-8 row-with-top">
					<img src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZxtopl_QGtoLsfR_aHTV-5ELCjHqrJ_2rwWNu_6X0Fl_TAAxa" style="width:100%;" >
					<%#= image_tag "sample_bounty_img.jpg", style:"width:100%;" %>
				</div>
				<div class = "col-md-4 row-with-top right-col">
					<div class ="token-sale">Token sale</div>
					<div class = "sale-date"><%=@bounty.sale_starts %></div>
					<div class = "goal-div">
						<div class = "blue-text-goal"><%=@bounty.goal %></div>
						<div class = "goal-text">GOAL</div>
					</div>
					<button class = "btn btn-sm btn-primary">Website</button>
					<br/><br/>
					<button class = "btn btn-sm btn-primary">Whitepaper</button>
				</div>
				</div>
			</div>
			<div class="separator"></div>
			<div class = "col-xs-12" style="background:#fff;padding:40px;box-shadow: 0 2px 6px rgba(0,0,0,.1);margin:0px;">
			<div class = "row list">
				<!-- <h3>Token Sale :<%#= @bounty.sale_starts %></h3> -->
				<div class = "col-md-6">
					<li><span class="grey">Ticker: </span><%=@bounty.ticker %></li>
					<li><span class="grey">Token type: </span><%=@bounty.token_type %></li>
					<li><span class="grey">ICO Token Price: </span><%=@bounty.ico_token_price%></li>
					<li><span class="grey">Fundraising Goal: </span> <%= @bounty.fundraising_goal %></li>
					<li><span class="grey">Total Tokens: </span> <%=@bounty.total_tokens %></li>
					<li><span class="grey">Start Time: </span> <%=@bounty.start_time %></li>
				</div>
				<div class = "col-md-6">
					<li><span class="grey">Whitelist: </span> <%= @bounty.whitelist== true ? "Yes" : "No" %></li>
					<li><span class="grey">Know Your Customer(KYC): </span> <%= @bounty.kyc== true ? "Yes" : "No" %></li>
					<li><span class="grey">Token Issue: </span> <%=@bounty.toke_issue%></li>
					<li><span class="grey">Accepts: </span> <%= @bounty.accepts %></li>
					<li><span class="grey">Available for Token Sale: </span> <%= @bounty.available_for_token_sale %></li>
					<li><span class="grey">End Time: </span> <%= @bounty.start_time %></li>
				</div>
				
			</div>
			</div>
			<div class="separator"></div>
			<div class = "col-xs-12" style="background:#fff;padding:40px;box-shadow: 0 2px 6px rgba(0,0,0,.1);margin:0px;">
			<div class = "row list">
				<!-- <h3>Token Sale :<%#= @bounty.sale_starts %></h3> -->
				<div class = "col-md-6">
					<li><span class="grey">Social Activity Level: </span><%=@bounty.social_activiti_level %></li>
					<li><span class="grey">Number of Team Members: </span><%=@bounty.no_of_team_members %></li>
					<li><span class="grey">ICO Active from: </span><%=@bounty.ico_active_from %></li>
					<li><span class="grey">Escrow: </span><%= @bounty.escrow %></li>
				</div>
				<div class = "col-md-6">
					<li><span class="grey">Prototype: </span><%= @bounty.prototypr %></li>
					<li><span class="grey">Role of Token: </span><%= @bounty.role_of_token %></li>
					<li><span class="grey">Token Issue: </span><%=@bounty.toke_issue%></li>
					<li><span class="grey">Rewords for: </span><%= @bounty.rewords_for %></li>
					<li><span class="grey">instruction: </span><%= @bounty.instruction %></li>
				</div>
			</div>
			</div>
		</div>
		<!-- <div class ="col-lg-10 col-lg-1-offset text-justify"> -->

			
			<%#= @bounty.short_explanation %>
		<!-- </div> -->
	</div>
	<!-- <div class="row"> -->
		<!-- <div class = "col-sm-12 col-md-4 col-md-offset-4"> -->
			
		<!-- </div> -->
	<!-- </div> -->
</artcle>
<div class = "row">
<div class = "col-lg-10 col-lg-offset-1">
<!-- <div class="comment-section"> -->
	<div id="comment_list">
	  <%= render 'comments/comments' %>
	</div>
	<% unless current_user.blank? %>
	  <%= render 'comments/form', comment: @comment %>
	<% else %>
	  <!-- <div style="margin-top: 5%;text-align:center;padding-bottom: 5%;"> -->
	  	<div class="col-xs-12" style = "text-align:center;">
	  		<br/><br/>
	  		<a href="/users/sign_in">
		      <input type="button" class="btn btn-info" value="Login to comment" style="width: 40%;font-size: 20px;">
		    </a>
		    <br/><br/>
		  </div>
		<!-- </div> -->
	<% end %>
<!-- </div> -->
</div>
</div>
<%= javascript_include_tag "bootstrap.min.js" %>
<style type="text/css">
	.separator {
 	height: 1px;
 	background-color: #f6f6f6;
 	margin:0px;
 	padding:0px;
 }
.row-with-top{
	margin-top:45px !important;
	margin-bottom:5px !important;
}
.right-col{
  border-radius: 2px;
  border: 1px solid #ededed;
  padding: 25px 15px 4px 15px;
  margin: 0 auto;
  min-width: 220px;
  font-family: 'Rajdhani',sans-serif;
  font-weight: 500;
  text-align: center;
}
.token-sale{
	text-align: center;
}
.sale-date{
	text-align: center;
	height: 50px;
	margin-top: 15px;
	text-transform: uppercase;
}
.goal-div{
	height: 79px;
}
.blue-text-goal{
	  text-align: center;
	  font-size: 22px;
	  font-weight: 900;
	  color: #2f80ed;
}
.goal-text{
	  text-align: center;
  font-weight: bold;
  font-size: 16px;
  color: rgba(0,0,0,.55);
}
.bounty-mon-row{
	display: flex;
	flex-direction: row;
	justify-content: flex-start;
}
.row{
	display: flex;
  /*-ms-flex-wrap: wrap;*/
  /*flex-wrap: wrap;*/
  margin-right: -15px;
  margin-left: -15px;
}
.list li{
	padding: 6px 0;
	  font-weight: 700;
	  text-transform: uppercase;
	  display: inline-block;
	  width: 100%;
}
.grey{
	opacity: 1;
  color: rgba(0,0,0,.55);
}
.list li span{
	text-transform: none;
	font-weight: 400;
	font-family: 'Roboto',sans-serif;
}
</style>